
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 19 22:19:51 CST 2020
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int cadena = 5;
  public static final int decimal = 4;
  public static final int print = 14;
  public static final int pcoma = 13;
  public static final int por = 8;
  public static final int else_ = 28;
  public static final int false_ = 20;
  public static final int break_ = 26;
  public static final int pCierra = 16;
  public static final int llaveAbre = 22;
  public static final int menos = 7;
  public static final int menor = 25;
  public static final int while_ = 21;
  public static final int div = 9;
  public static final int igual = 12;
  public static final int double_ = 11;
  public static final int EOF = 0;
  public static final int id = 2;
  public static final int true_ = 19;
  public static final int llaveCierra = 23;
  public static final int pAbre = 15;
  public static final int boolean_ = 17;
  public static final int error = 1;
  public static final int if_ = 27;
  public static final int String_ = 18;
  public static final int entero = 3;
  public static final int mas = 6;
  public static final int int_ = 10;
  public static final int mayor = 24;
}

